#!/usr/bin/env python3
"""
Coverage Baseline Generation Script
====================================

Purpose: Generate accurate, measured coverage baseline from full test suite execution

This script:
1. Parses pytest coverage.json output
2. Extracts module-level and file-level metrics
3. Stores structured baseline at ci/coverage_baseline.json
4. Generates human-readable report

Requirements: R3 (Establish Accurate Coverage Baseline)
Task: 2.1 Create coverage baseline generation script
"""

import json
import sys
from dataclasses import asdict, dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

# ============================================================================
# DATA MODELS
# ============================================================================


@dataclass
class FileCoverage:
    """Coverage data for a single source file"""

    file_path: str
    statements: int
    missed: int
    coverage_percent: float
    missing_lines: list[int] = field(default_factory=list)


@dataclass
class ModuleCoverage:
    """Coverage data for a single production module"""

    module_name: str
    statements: int
    missed: int
    coverage_percent: float
    critical_files: list[FileCoverage] = field(default_factory=list)


@dataclass
class CoverageBaseline:
    """Complete coverage baseline snapshot"""

    measurement_date: str
    pytest_version: str
    test_count: int
    overall_coverage: float
    modules: dict[str, ModuleCoverage]
    measurement_command: str
    python_version: str

    def to_json(self) -> str:
        """Serialize to JSON for storage"""
        return json.dumps(asdict(self), indent=2, ensure_ascii=False)

    @classmethod
    def from_json(cls, json_str: str) -> "CoverageBaseline":
        """Deserialize from JSON"""
        data = json.loads(json_str)
        # Convert nested dicts back to dataclasses
        modules = {}
        for mod_name, mod_data in data["modules"].items():
            critical_files = [FileCoverage(**f) for f in mod_data["critical_files"]]
            mod_data["critical_files"] = critical_files
            modules[mod_name] = ModuleCoverage(**mod_data)
        data["modules"] = modules
        return cls(**data)


# ============================================================================
# COVERAGE PARSING
# ============================================================================


def parse_coverage_json(coverage_path: Path) -> dict[str, Any]:
    """Parse coverage.json file generated by pytest-cov"""
    if not coverage_path.exists():
        raise FileNotFoundError(f"Coverage file not found: {coverage_path}")

    with open(coverage_path, "r", encoding="utf-8") as f:
        return json.load(f)


def extract_module_name(file_path: str) -> str:
    """Extract top-level module name from file path"""
    # Example: mahoun/core/fortress_validator.py -> core
    # Example: mahoun/reasoning/verdict_engine_adapter.py -> reasoning
    parts = file_path.split("/")
    if len(parts) >= 2 and parts[0] == "mahoun":
        return parts[1]
    return "unknown"


def calculate_coverage_percent(statements: int, missed: int) -> float:
    """Calculate coverage percentage"""
    if statements == 0:
        return 0.0
    return round(((statements - missed) / statements) * 100, 2)


def aggregate_module_coverage(coverage_data: dict[str, Any]) -> dict[str, ModuleCoverage]:
    """Aggregate file-level coverage into module-level coverage"""
    files = coverage_data.get("files", {})

    module_stats: dict[str, dict[str, Any]] = {}

    for file_path, file_data in files.items():
        # Only process mahoun/* files
        if not file_path.startswith("mahoun/"):
            continue

        module_name = extract_module_name(file_path)
        if module_name == "unknown":
            continue

        summary = file_data.get("summary", {})
        statements = summary.get("num_statements", 0)
        missed = summary.get("missing_lines", 0)
        if isinstance(missed, list):
            missed = len(missed)

        # Aggregate
        if module_name not in module_stats:
            module_stats[module_name] = {
                "statements": 0,
                "missed": 0,
                "files": [],
            }

        module_stats[module_name]["statements"] += statements
        module_stats[module_name]["missed"] += missed

        # Store file coverage for critical files (< 50% coverage)
        coverage_pct = calculate_coverage_percent(statements, missed)
        if coverage_pct < 50.0:
            missing_lines_data = file_data.get("missing_lines", [])
            if isinstance(missing_lines_data, dict):
                missing_lines = list(missing_lines_data.keys())
            else:
                missing_lines = missing_lines_data if isinstance(missing_lines_data, list) else []

            file_cov = FileCoverage(
                file_path=file_path,
                statements=statements,
                missed=missed,
                coverage_percent=coverage_pct,
                missing_lines=missing_lines[:20],  # Limit to first 20 lines
            )
            module_stats[module_name]["files"].append(file_cov)

    # Convert to ModuleCoverage objects
    modules = {}
    for module_name, stats in module_stats.items():
        coverage_pct = calculate_coverage_percent(stats["statements"], stats["missed"])
        modules[module_name] = ModuleCoverage(
            module_name=module_name,
            statements=stats["statements"],
            missed=stats["missed"],
            coverage_percent=coverage_pct,
            critical_files=stats["files"],
        )

    return modules


def get_pytest_version() -> str:
    """Get pytest version"""
    try:
        import pytest

        return pytest.__version__
    except Exception:
        return "unknown"


def get_python_version() -> str:
    """Get Python version"""
    return f"{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}"


def count_tests_from_log(log_path: Path) -> int:
    """Extract test count from pytest log file"""
    if not log_path.exists():
        return 0

    try:
        with open(log_path, "r", encoding="utf-8") as f:
            content = f.read()
            # Look for "collected X items" pattern
            import re

            match = re.search(r"collected (\d+) items?", content)
            if match:
                return int(match.group(1))
    except Exception:
        pass

    return 0


# ============================================================================
# BASELINE GENERATION
# ============================================================================


def generate_baseline(
    coverage_path: Path,
    output_path: Path,
    test_count: int | None = None,
) -> CoverageBaseline:
    """
    Generate coverage baseline from coverage.json

    Args:
        coverage_path: Path to coverage.json
        output_path: Path to store baseline JSON
        test_count: Optional test count (will try to detect if None)

    Returns:
        CoverageBaseline object
    """
    print(f"Parsing coverage data from {coverage_path}")
    coverage_data = parse_coverage_json(coverage_path)

    print("Aggregating module-level coverage...")
    modules = aggregate_module_coverage(coverage_data)

    # Calculate overall coverage
    total_statements = sum(m.statements for m in modules.values())
    total_missed = sum(m.missed for m in modules.values())
    overall_coverage = calculate_coverage_percent(total_statements, total_missed)

    # Detect test count if not provided
    if test_count is None:
        log_path = coverage_path.parent / "coverage_baseline_run.log"
        test_count = count_tests_from_log(log_path)
        if test_count == 0:
            print("⚠️  Warning: Could not detect test count, using 0")

    baseline = CoverageBaseline(
        measurement_date=datetime.now(UTC).isoformat(),
        pytest_version=get_pytest_version(),
        test_count=test_count,
        overall_coverage=overall_coverage,
        modules=modules,
        measurement_command="pytest tests/ --cov=mahoun --cov-report=json --cov-report=html --cov-report=term-missing -v",
        python_version=get_python_version(),
    )

    # Save baseline
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(baseline.to_json())

    print(f"✅ Baseline saved to {output_path}")

    return baseline


def print_baseline_summary(baseline: CoverageBaseline):
    """Print human-readable baseline summary"""
    print("\n" + "=" * 80)
    print("COVERAGE BASELINE SUMMARY")
    print("=" * 80)
    print(f"Measurement Date:    {baseline.measurement_date}")
    print(f"Python Version:      {baseline.python_version}")
    print(f"Pytest Version:      {baseline.pytest_version}")
    print(f"Test Count:          {baseline.test_count}")
    print(f"Overall Coverage:    {baseline.overall_coverage:.2f}%")
    print(f"Modules Analyzed:    {len(baseline.modules)}")
    print()

    print("MODULE COVERAGE:")
    print("-" * 80)
    print(f"{'Module':<25} {'Statements':>12} {'Missed':>10} {'Coverage':>12}")
    print("-" * 80)

    # Sort by coverage (lowest first)
    sorted_modules = sorted(baseline.modules.items(), key=lambda x: x[1].coverage_percent)

    for module_name, module_cov in sorted_modules:
        print(
            f"{module_name:<25} {module_cov.statements:>12} {module_cov.missed:>10} {module_cov.coverage_percent:>11.2f}%"
        )

    print("-" * 80)
    print()

    # Show lowest coverage modules
    print("LOWEST COVERAGE MODULES (< 30%):")
    print("-" * 80)
    low_coverage = [m for m in sorted_modules if m[1].coverage_percent < 30.0]
    if low_coverage:
        for module_name, module_cov in low_coverage[:10]:
            print(f"  {module_name:<20} {module_cov.coverage_percent:>6.2f}%")
            if module_cov.critical_files:
                print(f"    Critical files: {len(module_cov.critical_files)}")
                for f in module_cov.critical_files[:3]:
                    print(f"      - {f.file_path} ({f.coverage_percent:.1f}%)")
    else:
        print("  No modules with < 30% coverage")

    print("=" * 80)


# ============================================================================
# MAIN
# ============================================================================


def main():
    """Main execution"""
    import argparse

    parser = argparse.ArgumentParser(description="Generate coverage baseline from pytest-cov output")
    parser.add_argument(
        "--input",
        type=Path,
        default=Path("coverage.json"),
        help="Path to coverage.json (default: coverage.json)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("ci/coverage_baseline.json"),
        help="Path to output baseline JSON (default: ci/coverage_baseline.json)",
    )
    parser.add_argument(
        "--test-count",
        type=int,
        default=None,
        help="Test count (will auto-detect if not provided)",
    )

    args = parser.parse_args()

    try:
        baseline = generate_baseline(
            coverage_path=args.input,
            output_path=args.output,
            test_count=args.test_count,
        )

        print_baseline_summary(baseline)

        print(f"\n✅ Coverage baseline generation complete!")
        print(f"   Baseline: {args.output}")
        print(f"   Modules: {len(baseline.modules)}")
        print(f"   Overall: {baseline.overall_coverage:.2f}%")

        return 0

    except Exception as e:
        print(f"❌ Error generating baseline: {e}", file=sys.stderr)
        import traceback

        traceback.print_exc()
        return 1


if __name__ == "__main__":
    sys.exit(main())
